#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <SDL/SDL.h>
#include <math.h>
#include "SDL_gfxPrimitives.h"
#include <SDL/SDL.h>
#include "SDL_ttf.h"
#include "SDL_thread.h"
#include "SDL_mutex.h"
